export { default as Home } from "./Home/Home";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Footer } from "./Footer/Footer";
export { default as Contact } from "./Contact/Contact";
export { default as Banner } from "./Banner/Banner";
export { default as About } from "./About/About";
export { default as Services } from "./Services/Services";
export { default as Modal } from "./Modal/Modal";
export { default as Upload } from "./Upload/Upload";
